config/routes.rb
Rails.application.routes.draw do
  resources :activities
  resources :users, only:[:new, :create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  #get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  #get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  root to:"static_pages#index"

  get 'sobre', to: "static_pages#sobre"

  get 'contato', to: "static_pages#contato"
  
  get 'cadastro', to: 'users#new'

end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord

    has_secure_password

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

    validates :name, presence: true, length: { maximum: 50 }
    validates :password, length: { minimum: 6 }
    validates :email, presence: true, length: { maximum: 255 },
                                      format: { with: VALID_EMAIL_REGEX },
                                      uniqueness: { case_sensitive: true }
  


end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: %i[ show edit update destroy ]

  # GET /activities or /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1 or /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities or /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: "Activity was successfully created." }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1 or /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: "Activity was successfully updated." }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1 or /activities/1.json
  def destroy
    @activity.destroy!

    respond_to do |format|
      format.html { redirect_to activities_path, status: :see_other, notice: "Activity was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def activity_params
      params.require(:activity).permit(:nome, :user_id, :descricao, :data_hora_inicio, :data_hora_termino, :status)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

    def index
        @nome = "Leo"
    end

    def sobre

    end

    def contato
        
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
       @user = User.new(user_params)
       if @user.save
         flash[:success] = "Usuario cadastrado com sucesso"
         redirect_to  root_url
       else
         render 'new'
       end       
    end

    private
    def user_params
         params.require(:user).permit(:name,:email, :password, :password_confirmation)    
      
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/_activity.html.erb
<div id="<%= dom_id activity %>">
  <p>
    <strong>Nome:</strong>
    <%= activity.nome %>
  </p>

  <p>
    <strong>User:</strong>
    <%= activity.user_id %>
  </p>

  <p>
    <strong>Descricao:</strong>
    <%= activity.descricao %>
  </p>

  <p>
    <strong>Data hora inicio:</strong>
    <%= activity.data_hora_inicio %>
  </p>

  <p>
    <strong>Data hora termino:</strong>
    <%= activity.data_hora_termino %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= activity.status %>
  </p>

</div>

app/views/activities/_form.html.erb
<%= form_with(model: activity) do |form| %>
  <% if activity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
        <% activity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :descricao, style: "display: block" %>
    <%= form.text_field :descricao %>
  </div>

  <div>
    <%= form.label :data_hora_inicio, style: "display: block" %>
    <%= form.datetime_field :data_hora_inicio %>
  </div>

  <div>
    <%= form.label :data_hora_termino, style: "display: block" %>
    <%= form.datetime_field :data_hora_termino %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.number_field :status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<% content_for :title, "Editing activity" %>

<h1>Editing activity</h1>

<%= render "form", activity: @activity %>

<br>

<div>
  <%= link_to "Show this activity", @activity %> |
  <%= link_to "Back to activities", activities_path %>
</div>

app/views/activities/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Activities" %>

<h1>Activities</h1>

<div id="activities">
  <% @activities.each do |activity| %>
    <%= render activity %>
    <p>
      <%= link_to "Show this activity", activity %>
    </p>
  <% end %>
</div>

<%= link_to "New activity", new_activity_path %>

app/views/activities/new.html.erb
<% content_for :title, "New activity" %>

<h1>New activity</h1>

<%= render "form", activity: @activity %>

<br>

<div>
  <%= link_to "Back to activities", activities_path %>
</div>

app/views/activities/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @activity %>

<div>
  <%= link_to "Edit this activity", edit_activity_path(@activity) %> |
  <%= link_to "Back to activities", activities_path %>

  <%= button_to "Destroy this activity", @activity, method: :delete %>
</div>

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="">
    <div class="alert alert-danger">
      Ops! Encontramos <%= pluralize(object.errors.count, 'erro', 'erros') %>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <%= link_to 'Contact List. Todos os direitos reservados.', root_path %>
  </small>

  <nav>
    <ul>
      <li>
        <%= link_to 'Sobre', sobre_path %>
      </li>
      <li>
        <%= link_to 'Contato', contato_url %>
      </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary custom-navbar">
  <style>
    .custom-navbar {
      border-bottom: 1px solid rgb(87, 84, 84); /* Adiciona a borda superior */
      background-color: #f8f9fa; /* Exemplo de cor de fundo */
      padding-top: 10px; /* Ajusta o espaçamento */
    }
  </style>

  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      <span class="sr-only">Toggle navigation</span>
    </button>

    <%= link_to 'Contact List', root_url, class: 'navbar-brand' %>

    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
         <li class="active">
          <%= link_to 'Nova Conta', new_user_path %>
        </li>
      </ul>
      <span class="nav navbar-nav navbar-right">
         <li class="nav-item">
          <%= link_to 'Entrar', '#' %>
        </li>
      </span>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Agenda Eletronica" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>


    <%= render "layouts/header" %>

     <div class="container">


      <% flash.each do |message_type, message| %>
      <%= content_tag 'div', class: "alert alert-#{message_type} alert-dismissible", role: 'alert' do %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= message %>
      <% end %>
      <% end %>

      
      <%= yield %>
      <%= render "layouts/footer" %>
     
     </div>

  </body>
</html>

app/views/static_pages/contato.html.erb
<h1> Contato</h1>

<p>

Entre em Contato <a href= "www.google.com">Leonardo</a>

</p>

app/views/static_pages/index.html.erb
<br>
<br>

<div class="jumbotron">
    <h1>Agenda Eletronica</h1>
    <p>
      Gerencie sua agenda  em qualquer lugar!
    </p>
    <p>
      <%= link_to 'Crie Sua Conta', new_user_path, class: 'btn btn-primary btn-lg' %>
    </p>
  </div>

app/views/static_pages/sobre.html.erb
<h1>Sobre</h1>

<p>SUA  AGENDA  DE  ATIVIDADES  JAMAIS SERA A MESMA </p>

app/views/users/new.html.erb
<div class="row">
    <div class="col-xs-12">
      <h1>Cadastra-se</h1>
</div>

<div class="col-md-6 col-md-offset-3 col-xs-12">
     
  <%= form_for @user do |f| %>
   
  <%= render 'layouts/error_messages', object: f.object %>
  
    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

    <%= f.submit 'Cadastrar', class: 'btn btn-primary'%>
     
    <% end%>
</div>